In [1]:
import pandas as pd
import numpy as np

In [2]:
listings = pd.read_csv("D:/Talent assessment/Data/raw/listings.csv")
calendar = pd.read_csv("D:/Talent assessment/Data/raw/calendar.csv")
reviews = pd.read_csv("D:/Talent assessment/Data/raw/reviews.csv")
neighbourhoods = pd.read_csv("D:/Talent assessment/Data/raw/neighbourhoods.csv")

In [3]:
print("="*60)
print("LISTINGS DATASET")
print("="*60)

listings.head()

============================================================
LISTINGS DATASET
============================================================

,id,listing_url,scrape_id,last_scraped,source,name,description,neighborhood_overview,picture_url,host_id,...,review_scores_communication,review_scores_location,review_scores_value,license,instant_bookable,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month
0,52113003,https://www.airbnb.com/rooms/52113003,20260615212204,2026-06-16,city scrape,King Bed Loft in the Heart of Downtown Boston,"Welcome to our spacious, open-concept loft in ...",NaN,https://a0.muscache.com/pictures/b9802ab5-b0ef...,20828559,...,4.99,4.89,4.84,STR-516048,NaN,1,1,0,0,4.77
1,695542274861997846,https://www.airbnb.com/rooms/695542274861997846,20260615212204,2026-06-16,city scrape,Super 2 Bedroom apt in Beacon Hill Boston,Keep it simple at this peaceful and centrally-...,NaN,https://a0.muscache.com/pictures/miso/Hosting-...,373675137,...,5.00,5.00,5.00,NaN,NaN,117,53,64,0,0.11
2,9110708,https://www.airbnb.com/rooms/9110708,20260615212204,2026-07-06,previous scrape,Cozy & sunny apartment BU/Allston,"Cozy 1BR, 1BA apartment in central area of All...",NaN,https://a0.muscache.com/pictures/8b1a6c2f-3135...,32018716,...,NaN,NaN,NaN,NaN,NaN,1,1,0,0,NaN
3,197972,https://www.airbnb.com/rooms/197972,20260615212204,2026-06-16,city scrape,Serene Studio in a Perfect Location,"Our 500 sf 2 room apartment is quiet, private ...",NaN,https://a0.muscache.com/pictures/hosting/Hosti...,965697,...,4.97,4.92,4.81,STR-409453,NaN,2,2,0,0,3.33
4,706445990952752456,https://www.airbnb.com/rooms/706445990952752456,20260615212204,2026-06-16,city scrape,Spacious 1br In Boston FIDI | Close to T!,This wonderful 1 bedroom apartment is located ...,NaN,https://a0.muscache.com/pictures/miso/Hosting-...,382451810,...,4.91,4.91,4.63,STR-489695,NaN,43,43,0,0,4.21

In [4]:
print("="*60)
print("CALENDAR DATASET")
print("="*60)

calendar.head()

============================================================
CALENDAR DATASET
============================================================

   listing_id        date available  minimum_nights  maximum_nights
0        3781  2026-06-16         f              29            1125
1        3781  2026-06-17         f              29            1125
2        3781  2026-06-18         f              29            1125
3        3781  2026-06-19         f              29            1125
4        3781  2026-06-20         f              29            1125

In [5]:
print("="*60)
print("REVIEWS DATASET")
print("="*60)

reviews.head()

============================================================
REVIEWS DATASET
============================================================

,listing_id,id,date,reviewer_id,reviewer_name,comments
0,3781,37776825,2015-07-10,36059247,Greg,The apartment was as advertised and Frank was ...
1,3781,41842494,2015-08-09,10459388,Tai,It was a pleasure to stay at Frank's place. Th...
2,3781,45282151,2015-09-01,12264652,Damien,The apartment description is entirely faithful...
3,3781,49022647,2015-09-30,41426327,Mike,Thoroughly enjoyed my time at Frank's home. Ha...
4,3781,52503327,2015-10-30,15151513,Ivan,Great value for the money! This location has e...

In [6]:
print("="*60)
print("NEIGHBOURHOODS DATASET")
print("="*60)

neighbourhoods.head()

============================================================
NEIGHBOURHOODS DATASET
============================================================

   neighbourhood_group neighbourhood
0                  NaN       Allston
1                  NaN      Back Bay
2                  NaN   Bay Village
3                  NaN   Beacon Hill
4                  NaN      Brighton

In [7]:
print("Listings Shape:", listings.shape)
print("Calendar Shape:", calendar.shape)
print("Reviews Shape:", reviews.shape)
print("Neighbourhoods Shape:", neighbourhoods.shape)

Listings Shape: (4378, 90)
Calendar Shape: (1611110, 5)
Reviews Shape: (252910, 6)
Neighbourhoods Shape: (26, 2)

In [8]:
print("="*60)
print("LISTINGS INFO")
print("="*60)

listings.info()

============================================================
LISTINGS INFO
============================================================
<class 'pandas.DataFrame'>
RangeIndex: 4378 entries, 0 to 4377
Data columns (total 90 columns):
 #   Column                                        Non-Null Count  Dtype
---  ------                                        --------------  -----
 0   id                                            4378 non-null   int64
 1   listing_url                                   4378 non-null   str
 2   scrape_id                                     4378 non-null   int64
 3   last_scraped                                  4378 non-null   str
 4   source                                        4378 non-null   str
 5   name                                          4378 non-null   str
 6   description                                   4319 non-null   str
 7   neighborhood_overview                         0 non-null      float64
 8   picture_url                                   4378 non-null   str
 9   host_id                                       4378 non-null   int64
 10  host_url                                      4378 non-null   str
 11  host_profile_id                               4360 non-null   float64
 12  host_profile_url                              4348 non-null   str
 13  host_name                                     4360 non-null   str
 14  host_since                                    0 non-null      float64
 15  hosts_time_as_user_years                      4360 non-null   float64
 16  hosts_time_as_user_months                     4360 non-null   float64
 17  hosts_time_as_host_years                      4360 non-null   float64
 18  hosts_time_as_host_months                     4360 non-null   float64
 19  host_location                                 3353 non-null   str
 20  host_about                                    2798 non-null   str
 21  host_response_time                            0 non-null      float64
 22  host_response_rate                            0 non-null      float64
 23  host_acceptance_rate                          0 non-null      float64
 24  host_is_superhost                             4360 non-null   str
 25  host_thumbnail_url                            0 non-null      float64
 26  host_picture_url                              4360 non-null   str
 27  host_neighbourhood                            0 non-null      float64
 28  host_listings_count                           4360 non-null   float64
 29  host_total_listings_count                     0 non-null      float64
 30  host_verifications                            0 non-null      float64
 31  host_has_profile_pic                          4360 non-null   str
 32  host_identity_verified                        4360 non-null   str
 33  neighbourhood                                 0 non-null      float64
 34  neighbourhood_cleansed                        4378 non-null   str
 35  neighbourhood_group_cleansed                  0 non-null      float64
 36  latitude                                      4378 non-null   float64
 37  longitude                                     4378 non-null   float64
 38  property_type                                 4378 non-null   str
 39  room_type                                     4378 non-null   str
 40  accommodates                                  4378 non-null   int64
 41  bathrooms                                     3348 non-null   float64
 42  bathrooms_text                                4343 non-null   str
 43  bedrooms                                      3117 non-null   float64
 44  beds                                          3449 non-null   float64
 45  amenities                                     4378 non-null   str
 46  price                                         3693 non-null   str
 47  price_quote_checkin_date                      3922 non-null   str
 48  price_quote_checkout_date                     3922 non-null   str
 49  price_quote_total_price                       3693 non-null   float64
 50  price_quote_price_per_night                   3693 non-null   float64
 51  price_quote_raw                               3922 non-null   str
 52  minimum_nights                                4378 non-null   int64
 53  maximum_nights                                4378 non-null   int64
 54  minimum_minimum_nights                        4378 non-null   int64
 55  maximum_minimum_nights                        4378 non-null   int64
 56  minimum_maximum_nights                        4378 non-null   int64
 57  maximum_maximum_nights                        4378 non-null   int64
 58  minimum_nights_avg_ntm                        4378 non-null   float64
 59  maximum_nights_avg_ntm                        4378 non-null   float64
 60  calendar_updated                              0 non-null      float64
 61  has_availability                              4345 non-null   str
 62  availability_30                               4378 non-null   int64
 63  availability_60                               4378 non-null   int64
 64  availability_90                               4378 non-null   int64
 65  availability_365                              4378 non-null   int64
 66  calendar_last_scraped                         4378 non-null   str
 67  number_of_reviews                             4378 non-null   int64
 68  number_of_reviews_ltm                         4378 non-null   int64
 69  number_of_reviews_l30d                        4378 non-null   int64
 70  availability_eoy                              4378 non-null   int64
 71  number_of_reviews_ly                          4378 non-null   int64
 72  estimated_occupancy_l365d                     4378 non-null   int64
 73  estimated_revenue_l365d                       3693 non-null   float64
 74  first_review                                  3477 non-null   str
 75  last_review                                   3477 non-null   str
 76  review_scores_rating                          3477 non-null   float64
 77  review_scores_accuracy                        3476 non-null   float64
 78  review_scores_cleanliness                     3477 non-null   float64
 79  review_scores_checkin                         3476 non-null   float64
 80  review_scores_communication                   3477 non-null   float64
 81  review_scores_location                        3476 non-null   float64
 82  review_scores_value                           3476 non-null   float64
 83  license                                       3150 non-null   str
 84  instant_bookable                              0 non-null      float64
 85  calculated_host_listings_count                4378 non-null   int64
 86  calculated_host_listings_count_entire_homes   4378 non-null   int64
 87  calculated_host_listings_count_private_rooms  4378 non-null   int64
 88  calculated_host_listings_count_shared_rooms   4378 non-null   int64
 89  reviews_per_month                             3477 non-null   float64
dtypes: float64(37), int64(24), str(29)
memory usage: 3.0 MB

In [9]:
print("="*60)
print("CALENDAR INFO")
print("="*60)

calendar.info()

============================================================
CALENDAR INFO
============================================================
<class 'pandas.DataFrame'>
RangeIndex: 1611110 entries, 0 to 1611109
Data columns (total 5 columns):
 #   Column          Non-Null Count    Dtype
---  ------          --------------    -----
 0   listing_id      1611110 non-null  int64
 1   date            1611110 non-null  str
 2   available       1611110 non-null  str
 3   minimum_nights  1611110 non-null  int64
 4   maximum_nights  1611110 non-null  int64
dtypes: int64(3), str(2)
memory usage: 61.5 MB

In [10]:
print("="*60)
print("REVIEWS INFO")
print("="*60)

reviews.info()

============================================================
REVIEWS INFO
============================================================
<class 'pandas.DataFrame'>
RangeIndex: 252910 entries, 0 to 252909
Data columns (total 6 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   listing_id     252910 non-null  int64
 1   id             252910 non-null  int64
 2   date           252910 non-null  str
 3   reviewer_id    252910 non-null  int64
 4   reviewer_name  252909 non-null  str
 5   comments       252838 non-null  str
dtypes: int64(3), str(3)
memory usage: 11.6 MB

In [11]:
print("="*60)
print("NEIGHBOURHOODS INFO")
print("="*60)

neighbourhoods.info()

============================================================
NEIGHBOURHOODS INFO
============================================================
<class 'pandas.DataFrame'>
RangeIndex: 26 entries, 0 to 25
Data columns (total 2 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   neighbourhood_group  0 non-null      float64
 1   neighbourhood        26 non-null     str
dtypes: float64(1), str(1)
memory usage: 548.0 bytes

In [12]:
print("="*60)
print("LISTINGS SUMMARY")
print("="*60)

listings.describe()

============================================================
LISTINGS SUMMARY
============================================================

,id,scrape_id,neighborhood_overview,host_id,host_profile_id,host_since,hosts_time_as_user_years,hosts_time_as_user_months,hosts_time_as_host_years,hosts_time_as_host_months,...,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value,instant_bookable,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month
count,4.378000e+03,4.378000e+03,0.0,4.378000e+03,4.360000e+03,0.0,4360.000000,4360.000000,4360.000000,4360.000000,...,3476.000000,3477.000000,3476.000000,3476.000000,0.0,4378.000000,4378.000000,4378.000000,4378.000000,3477.000000
mean,8.176489e+17,2.026062e+13,NaN,1.266426e+16,1.473194e+18,NaN,7.994725,5.775229,6.606881,5.677064,...,4.856392,4.848225,4.765570,4.625046,NaN,30.073550,24.379625,4.978986,0.009822,1.727291
std,6.442407e+17,0.000000e+00,NaN,1.453351e+17,3.387821e+16,NaN,4.064542,3.547266,4.179232,3.409409,...,0.317106,0.329988,0.327309,0.419755,NaN,52.975297,51.752829,12.400281,0.098629,1.882912
min,3.781000e+03,2.026062e+13,NaN,4.804000e+03,1.462506e+18,NaN,0.000000,0.000000,0.000000,0.000000,...,1.000000,1.000000,1.000000,1.000000,NaN,1.000000,0.000000,0.000000,0.000000,0.010000
25%,4.553112e+07,2.026062e+13,NaN,2.234822e+07,1.462889e+18,NaN,5.000000,3.000000,3.000000,3.000000,...,4.840000,4.840000,4.680000,4.520000,NaN,2.000000,1.000000,0.000000,0.000000,0.280000
50%,9.659016e+17,2.026062e+13,NaN,1.074344e+08,1.465718e+18,NaN,9.000000,6.000000,7.000000,6.000000,...,4.940000,4.940000,4.870000,4.720000,NaN,7.000000,3.000000,0.000000,0.000000,1.070000
75%,1.415532e+18,2.026062e+13,NaN,3.824518e+08,1.469716e+18,NaN,11.000000,9.000000,10.000000,9.000000,...,5.000000,5.000000,4.990000,4.860000,NaN,34.000000,19.000000,3.000000,0.000000,2.650000
max,1.706947e+18,2.026062e+13,NaN,1.694941e+18,1.706947e+18,NaN,17.000000,11.000000,15.000000,11.000000,...,5.000000,5.000000,5.000000,5.000000,NaN,227.000000,227.000000,64.000000,1.000000,24.160000

In [13]:
calendar.describe()

         listing_id  minimum_nights  maximum_nights
count  1.611110e+06    1.611110e+06    1.611110e+06
mean   8.222325e+17    2.083847e+01    3.359596e+06
std    6.440098e+17    3.088112e+01    8.486481e+07
min    3.781000e+03    1.000000e+00    1.000000e+00
25%    4.564134e+07    2.000000e+00    3.650000e+02
50%    9.702534e+17    4.000000e+00    3.650000e+02
75%    1.417683e+18    2.900000e+01    1.125000e+03
max    1.706947e+18    4.000000e+02    2.147484e+09

In [14]:
reviews.describe()

         listing_id            id   reviewer_id
count  2.529100e+05  2.529100e+05  2.529100e+05
mean   3.295656e+17  8.469943e+17  1.388176e+15
std    4.995459e+17  5.976584e+17  4.827080e+16
min    3.781000e+03  1.021000e+03  3.220000e+02
25%    1.552141e+07  7.243652e+08  4.902409e+07
50%    4.549395e+07  9.666564e+17  1.415557e+08
75%    7.499345e+17  1.393619e+18  3.365004e+08
max    1.701335e+18  1.722671e+18  1.715917e+18

In [15]:
print(listings.dtypes)

id                                                int64
listing_url                                         str
scrape_id                                         int64
last_scraped                                        str
source                                              str
                                                 ...
calculated_host_listings_count                    int64
calculated_host_listings_count_entire_homes       int64
calculated_host_listings_count_private_rooms      int64
calculated_host_listings_count_shared_rooms       int64
reviews_per_month                               float64
Length: 90, dtype: object

In [16]:
print(calendar.dtypes)

listing_id        int64
date                str
available           str
minimum_nights    int64
maximum_nights    int64
dtype: object

In [17]:
print(reviews.dtypes)

listing_id       int64
id               int64
date               str
reviewer_id      int64
reviewer_name      str
comments           str
dtype: object

In [18]:
print("="*60)
print("MISSING VALUES - LISTINGS")
print("="*60)

listings.isnull().sum()

============================================================
MISSING VALUES - LISTINGS
============================================================

id                                                0
listing_url                                       0
scrape_id                                         0
last_scraped                                      0
source                                            0
                                               ...
calculated_host_listings_count                    0
calculated_host_listings_count_entire_homes       0
calculated_host_listings_count_private_rooms      0
calculated_host_listings_count_shared_rooms       0
reviews_per_month                               901
Length: 90, dtype: int64

In [19]:
listings.isnull().sum().sort_values(ascending=False)

neighborhood_overview                           4378
host_since                                      4378
host_response_time                              4378
host_thumbnail_url                              4378
host_acceptance_rate                            4378
                                                ...
availability_30                                    0
calculated_host_listings_count                     0
calculated_host_listings_count_entire_homes        0
calculated_host_listings_count_private_rooms       0
calculated_host_listings_count_shared_rooms        0
Length: 90, dtype: int64

In [20]:
calendar.isnull().sum()

listing_id        0
date              0
available         0
minimum_nights    0
maximum_nights    0
dtype: int64

In [21]:
reviews.isnull().sum()

listing_id        0
id                0
date              0
reviewer_id       0
reviewer_name     1
comments         72
dtype: int64

In [22]:
neighbourhoods.isnull().sum()

neighbourhood_group    26
neighbourhood           0
dtype: int64

In [23]:
print("Listings Duplicates :", listings.duplicated().sum())
print("Calendar Duplicates :", calendar.duplicated().sum())
print("Reviews Duplicates :", reviews.duplicated().sum())
print("Neighbourhood Duplicates :", neighbourhoods.duplicated().sum())

Listings Duplicates : 0
Calendar Duplicates : 0
Reviews Duplicates : 0
Neighbourhood Duplicates : 0

In [24]:
print(listings["room_type"].unique())

<StringArray>
['Entire home/apt', 'Private room', 'Hotel room', 'Shared room']
Length: 4, dtype: str

In [25]:
print(listings["property_type"].unique())

<StringArray>
[                       'Entire loft',                 'Entire rental unit',
          'Entire serviced apartment',                      'Room in hotel',
                       'Entire condo',        'Private room in rental unit',
        'Private room in guest suite',                        'Entire home',
               'Private room in home',                  'Entire guesthouse',
                 'Entire guest suite',                   'Entire townhouse',
             'Room in boutique hotel',                'Shared room in home',
 'Private room in serviced apartment',  'Private room in bed and breakfast',
              'Private room in condo',          'Private room in townhouse',
                          'Houseboat',                          'Tiny home',
               'Private room in loft',              'Private room in villa',
         'Shared room in rental unit',                               'Boat',
                       'Entire place',                 'Room in aparthotel',
               'Entire vacation home',               'Shared room in condo',
           'Private room in bungalow']
Length: 29, dtype: str

In [26]:
print(listings["neighbourhood_group_cleansed"].unique())

[nan]

In [27]:
print(listings.nunique())

id                                              4378
listing_url                                     4378
scrape_id                                          1
last_scraped                                       3
source                                             2
                                                ...
calculated_host_listings_count                    41
calculated_host_listings_count_entire_homes       32
calculated_host_listings_count_private_rooms      23
calculated_host_listings_count_shared_rooms        2
reviews_per_month                                617
Length: 90, dtype: int64

In [28]:
print(listings["price"].head())

0    $347.40
1    $146.21
2        NaN
3    $203.51
4    $351.05
Name: price, dtype: str

In [29]:
print(listings["price"].describe())

count       3693
unique      2528
top       $87.87
freq          14
Name: price, dtype: object

In [30]:
numeric_columns = listings.select_dtypes(include=["int64", "float64"])

numeric_columns.head()

,id,scrape_id,neighborhood_overview,host_id,host_profile_id,host_since,hosts_time_as_user_years,hosts_time_as_user_months,hosts_time_as_host_years,hosts_time_as_host_months,...,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value,instant_bookable,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month
0,52113003,20260615212204,NaN,20828559,1.463140e+18,NaN,11.0,9.0,6.0,9.0,...,4.97,4.99,4.89,4.84,NaN,1,1,0,0,4.77
1,695542274861997846,20260615212204,NaN,373675137,1.463554e+18,NaN,5.0,7.0,5.0,7.0,...,5.00,5.00,5.00,5.00,NaN,117,53,64,0,0.11
2,9110708,20260615212204,NaN,32018716,1.465470e+18,NaN,11.0,2.0,10.0,8.0,...,NaN,NaN,NaN,NaN,NaN,1,1,0,0,NaN
3,197972,20260615212204,NaN,965697,1.462534e+18,NaN,14.0,10.0,14.0,8.0,...,4.96,4.97,4.92,4.81,NaN,2,2,0,0,3.33
4,706445990952752456,20260615212204,NaN,382451810,1.469783e+18,NaN,5.0,5.0,5.0,5.0,...,4.91,4.91,4.91,4.63,NaN,43,43,0,0,4.21

In [31]:
categorical_columns = listings.select_dtypes(include=["object"])

categorical_columns.head()

C:\Users\Sithmi\AppData\Local\Temp\ipykernel_28680\1169770722.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  categorical_columns = listings.select_dtypes(include=["object"])

,listing_url,last_scraped,source,name,description,picture_url,host_url,host_profile_url,host_name,host_location,...,amenities,price,price_quote_checkin_date,price_quote_checkout_date,price_quote_raw,has_availability,calendar_last_scraped,first_review,last_review,license
0,https://www.airbnb.com/rooms/52113003,2026-06-16,city scrape,King Bed Loft in the Heart of Downtown Boston,"Welcome to our spacious, open-concept loft in ...",https://a0.muscache.com/pictures/b9802ab5-b0ef...,https://www.airbnb.com/users/show/20828559,https://www.airbnb.com/users/profile/146313972...,Lu,"Boston, MA",...,"[""Cooking basics"", ""Paid parking garage off pr...",$347.40,2026-06-30,2026-07-02,"{""quote"": {""taxes"": null, ""currency"": ""USD"", ""...",t,2026-06-16,2021-09-15,2026-05-27,STR-516048
1,https://www.airbnb.com/rooms/695542274861997846,2026-06-16,city scrape,Super 2 Bedroom apt in Beacon Hill Boston,Keep it simple at this peaceful and centrally-...,https://a0.muscache.com/pictures/miso/Hosting-...,https://www.airbnb.com/users/show/373675137,https://www.airbnb.com/users/profile/146355420...,Lilith,"Boston, MA",...,"[""Cooking basics"", ""Smoke alarm"", ""Central hea...",$146.21,2026-09-01,2026-09-30,"{""quote"": {""taxes"": null, ""currency"": ""USD"", ""...",t,2026-06-16,2023-05-12,2024-12-09,NaN
2,https://www.airbnb.com/rooms/9110708,2026-07-06,previous scrape,Cozy & sunny apartment BU/Allston,"Cozy 1BR, 1BA apartment in central area of All...",https://a0.muscache.com/pictures/8b1a6c2f-3135...,https://www.airbnb.com/users/show/32018716,https://www.airbnb.com/users/profile/146547041...,Linh,"Ho Chi Minh City, Vietnam",...,"[""Washer"", ""Essentials"", ""Shampoo"", ""Wifi"", ""H...",NaN,NaN,NaN,NaN,t,2026-07-06,NaN,NaN,NaN
3,https://www.airbnb.com/rooms/197972,2026-06-16,city scrape,Serene Studio in a Perfect Location,"Our 500 sf 2 room apartment is quiet, private ...",https://a0.muscache.com/pictures/hosting/Hosti...,https://www.airbnb.com/users/show/965697,https://www.airbnb.com/users/profile/146253448...,Kristina,"Boston, MA",...,"[""Cooking basics"", ""Private patio or balcony"",...",$203.51,2026-06-30,2026-07-03,"{""quote"": {""taxes"": null, ""currency"": ""USD"", ""...",t,2026-06-16,2011-10-18,2026-06-06,STR-409453
4,https://www.airbnb.com/rooms/706445990952752456,2026-06-16,city scrape,Spacious 1br In Boston FIDI | Close to T!,This wonderful 1 bedroom apartment is located ...,https://a0.muscache.com/pictures/miso/Hosting-...,https://www.airbnb.com/users/show/382451810,https://www.airbnb.com/users/profile/146978325...,Healing Homes,"Boston, MA",...,"[""Cooking basics"", ""Central air conditioning"",...",$351.05,2026-06-24,2026-06-25,"{""quote"": {""taxes"": null, ""currency"": ""USD"", ""...",t,2026-06-16,2022-09-05,2026-05-21,STR-489695

In [32]:
listings.memory_usage(deep=True)

Index                                              132
id                                               35024
listing_url                                     407244
scrape_id                                        35024
last_scraped                                    258302
                                                 ...
calculated_host_listings_count                   35024
calculated_host_listings_count_entire_homes      35024
calculated_host_listings_count_private_rooms     35024
calculated_host_listings_count_shared_rooms      35024
reviews_per_month                                35024
Length: 91, dtype: int64

In [33]:
print(
    "Memory Usage:",
    round(listings.memory_usage(deep=True).sum() / 1024**2, 2),
    "MB"
)

Memory Usage: 19.17 MB

In [35]:
print(listings["price"].dtype)

str

In [36]:
print(listings["price"].head(10))

0    $347.40
1    $146.21
2        NaN
3    $203.51
4    $351.05
5    $167.03
6    $295.56
7    $269.10
8    $322.59
9    $171.66
Name: price, dtype: str

In [37]:
listings["price"] = (
    listings["price"]
    .astype(str)
    .str.replace("$", "", regex=False)
    .str.replace(",", "", regex=False)
)

listings["price"] = pd.to_numeric(
    listings["price"],
    errors="coerce"
)

In [38]:
print("Negative Prices")

print((listings["price"] <= 0).sum())

Negative Prices
0

In [39]:
print("Invalid Latitude")

print(
    ((listings["latitude"] < -90) |
    (listings["latitude"] > 90)).sum()
)

Invalid Latitude
0

In [40]:
print("Invalid Longitude")

print(
    ((listings["longitude"] < -180) |
    (listings["longitude"] > 180)).sum()
)

Invalid Longitude
0

In [41]:
review_columns = [
    "review_scores_rating",
    "review_scores_accuracy",
    "review_scores_cleanliness",
    "review_scores_checkin",
    "review_scores_communication",
    "review_scores_location",
    "review_scores_value",
    "reviews_per_month"
]

listings[review_columns].describe()

,review_scores_rating,review_scores_accuracy,review_scores_cleanliness,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value,reviews_per_month
count,3477.000000,3476.000000,3477.000000,3476.000000,3477.000000,3476.000000,3476.000000,3477.000000
mean,4.747230,4.779980,4.761481,4.856392,4.848225,4.765570,4.625046,1.727291
std,0.365785,0.349216,0.358597,0.317106,0.329988,0.327309,0.419755,1.882912
min,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.010000
25%,4.670000,4.730000,4.700000,4.840000,4.840000,4.680000,4.520000,0.280000
50%,4.850000,4.880000,4.870000,4.940000,4.940000,4.870000,4.720000,1.070000
75%,4.980000,4.980000,4.980000,5.000000,5.000000,4.990000,4.860000,2.650000
max,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,24.160000

In [42]:
numeric = listings.select_dtypes(include=np.number)

numeric.corr()

,id,scrape_id,neighborhood_overview,host_id,host_profile_id,host_since,hosts_time_as_user_years,hosts_time_as_user_months,hosts_time_as_host_years,hosts_time_as_host_months,...,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value,instant_bookable,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month
id,1.000000,NaN,NaN,0.116822,0.296180,NaN,-0.418089,-0.042244,-0.485781,-0.114742,...,-0.049149,-0.036558,0.006242,-0.030591,NaN,0.044041,0.026099,0.041748,-0.030483,0.179151
scrape_id,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
neighborhood_overview,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
host_id,0.116822,NaN,NaN,1.000000,0.534097,NaN,-0.171792,-0.119076,-0.138073,-0.139250,...,-0.049792,-0.048362,-0.018218,-0.043724,NaN,-0.031255,-0.023724,-0.029486,-0.008680,0.010715
host_profile_id,0.296180,NaN,NaN,0.534097,1.000000,NaN,-0.269069,-0.064229,-0.388052,-0.208445,...,-0.061887,-0.029717,-0.025095,-0.008149,NaN,-0.113111,-0.095014,-0.089589,-0.016766,0.050910
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
calculated_host_listings_count,0.044041,NaN,NaN,-0.031255,-0.113111,NaN,0.031440,0.053097,0.182364,0.069695,...,-0.139861,-0.153089,0.062230,-0.211138,NaN,1.000000,0.967810,0.217260,-0.024319,-0.081022
calculated_host_listings_count_entire_homes,0.026099,NaN,NaN,-0.023724,-0.095014,NaN,0.042112,0.059486,0.173392,0.062598,...,-0.143806,-0.128171,0.093632,-0.174327,NaN,0.967810,1.000000,-0.011870,-0.034300,-0.014172
calculated_host_listings_count_private_rooms,0.041748,NaN,NaN,-0.029486,-0.089589,NaN,0.030330,0.026884,0.107089,0.087031,...,-0.012458,-0.090506,-0.080035,-0.124382,NaN,0.217260,-0.011870,1.000000,0.036969,-0.189498
calculated_host_listings_count_shared_rooms,-0.030483,NaN,NaN,-0.008680,-0.016766,NaN,0.004127,-0.008726,0.016054,0.070049,...,-0.011624,-0.003980,-0.006987,-0.048594,NaN,-0.024319,-0.034300,0.036969,1.000000,-0.024913
reviews_per_month,0.179151,NaN,NaN,0.010715,0.050910,NaN,-0.179788,0.027289,-0.195224,-0.008077,...,0.070701,0.108347,0.095175,0.124691,NaN,-0.081022,-0.014172,-0.189498,-0.024913,1.000000

In [43]:
summary = pd.DataFrame({
    "Column": listings.columns,
    "Data Type": listings.dtypes.values,
    "Missing Values": listings.isnull().sum().values,
    "Unique Values": listings.nunique().values
})

summary.to_csv(
    "D:/Talent assessment/Data/exploration/listings_summary.csv",
    index=False
)

print("Exploration summary saved successfully.")

Exploration summary saved successfully.